---
title: "Latin_Final"
author: "Khalid"
date: "12/12/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(shiny)
library(shinythemes)
library(dplyr)
library(ggthemes)
library(gt)


```


```{r}
Catullus <- c("Passer, deliciae meae puellae,
quicum ludere, quem in sinu tenere,
cui primum digitum dare appetenti
et acris solet incitare morsus,
cum desiderio meo nitenti
carum nescio quid lubet iocari
et solaciolum sui doloris,
credo ut tum gravis acquiescat ardor:
tecum ludere sicut ipsa possem
et tristis animi levare curas!",

"Vivamus mea Lesbia, atque amemus,
rumoresque senum severiorum
omnes unius aestimemus assis!
soles occidere et redire possunt:
nobis cum semel occidit brevis lux,
nox est perpetua una dormienda.
da mi basia mille, deinde centum,
dein mille altera, dein secunda centum,
deinde usque altera mille, deinde centum.
dein, cum milia multa fecerimus,
conturbabimus illa, ne sciamus,
aut ne quis malus invidere possit,
cum tantum sciat esse basiorum.",

"Multas per gentes et multa per aequora vectus
     advenio has miseras, frater, ad inferias,
ut te postremo donarem munere mortis
     et mutam nequiquam alloquerer cinerem.
quandoquidem fortuna mihi tete abstulit ipsum.
     heu miser indigne frater adempte mihi,
nunc tamen interea haec, prisco quae more parentum
     tradita sunt tristi munere ad inferias,
accipe fraterno multum manantia fletu,
     atque in perpetuum, frater, ave atque vale.")

Cicero <- c("I. Quo usque tandem abutere, Catilina, patientia nostra? quam diu etiam furor iste tuus nos eludet? quem ad finem sese effrenata iactabit audacia? Nihilne te nocturnum praesidium Palati, nihil urbis vigiliae, nihil timor populi, nihil concursus bonorum omnium, nihil hic munitissimus habendi senatus locus, nihil horum ora voltusque moverunt? Patere tua consilia non sentis, constrictam iam horum omnium scientia teneri coniurationem tuam non vides? Quid proxima, quid superiore nocte egeris, ubi fueris, quos convocaveris, quid consilii ceperis, quem nostrum ignorare arbitraris? [2] O tempora, o mores! Senatus haec intellegit. Consul videt; hic tamen vivit. Vivit? immo vero etiam in senatum venit, fit publici consilii particeps, notat et designat oculis ad caedem unum quemque nostrum. Nos autem fortes viri satis facere rei publicae videmur, si istius furorem ac tela vitemus. Ad mortem te, Catilina, duci iussu consulis iam pridem oportebat, in te conferri pestem, quam tu in nos [omnes iam diu] machinaris.",

"Tandem aliquando, Quirites, L. Catilinam furentem audacia, scelus anhelantem, pestem patriae nefarie molientem, vobis atque huic urbi ferro flammaque minitantem ex urbe vel eiecimus vel emisimus vel ipsum egredientem verbis prosecuti sumus. Abiit, excessit, evasit, erupit. Nulla iam pernicies a monstro illo atque prodigio moenibus ipsis intra moenia comparabitur. Atque hunc quidem unum huius belli domestici ducem sine controversia vicimus. Non enim iam inter latera nostra sica illa versabitur, non in campo, non in foro, non in curia, non denique intra domesticos parietes pertimescemus. Loco ille motus est, cum est ex urbe depulsus. Palam iam cum hoste nullo inpediente bellum iustum geremus. Sine dubio perdidimus hominem magnificeque vicimus, cum illum ex occultis insidiis in apertum latrocinium coniecimus.",

"Rem publicam, Quirites, vitamque omnium vestrum, bona, fortunas, coniuges liberosque vestros atque hoc domicilium clarissimi imperii, fortunatissimam pulcherrimamque urbem, hodierno die deorum immortalium summo erga vos amore, laboribus, consiliis, periculis meis e flamma atque ferro ac paene ex faucibus fati ereptam et vobis conservatam ac restitutam videtis.")




Sallust <- c(" Omnis homines, qui sese student praestare ceteris animalibus, summa ope niti decet, ne vitam silentio transeant veluti pecora, quae natura prona atque ventri oboedientia finxit. 2 Sed nostra omnis vis in animo et corpore sita est: animi imperio, corporis servitio magis utimur; alterum nobis cum dis, alterum cum beluis commune est. 3 Quo mihi rectius videtur ingeni quam virium opibus gloriam quaerere et, quoniam vita ipsa, qua fruimur, brevis est, memoriam nostri quam maxume longam efficere. 4 Nam divitiarum et formae gloria fluxa atque fragilis est, virtus clara aeternaque habetur.

5 Sed diu magnum inter mortalis certamen fuit, vine corporis an virtute animi res militaris magis procederet. 6 Nam et, prius quam incipias, consulto et, ubi consulueris, mature facto opus est. 7 Ita utrumque per se indigens alterum alterius auxilio eget.",

" 1 Igitur initio reges – nam in terris nomen imperi id primum fuit – divorsi pars ingenium, alii corpus exercebant: etiam tum vita hominum sine cupiditate agitabatur; sua cuique satis placebant. 2 Postea vero quam in Asia Cyrus, in Graecia Lacedaemonii et Athenienses coepere urbis atque nationes subigere, lubidinem dominandi causam belli habere, maxumam gloriam in maxumo imperio putare, tum demum periculo atque negotiis compertum est in bello plurumum ingenium posse. 3 Quod si regum atque imperatorum animi virtus in pace ita ut in bello valeret, aequabilius atque constantius sese res humanae haberent neque aliud alio ferri neque mutari ac misceri omnia cerneres. 4 Nam imperium facile iis artibus retinetur, quibus initio partum est. 5 Verum ubi pro labore desidia, pro continentia et aequitate lubido atque superbia invasere, fortuna simul cum moribus inmutatur. 6 Ita imperium semper ad optumum quemque a minus bono transfertur.

7 Quae homines arant, navigant, aedificant, virtuti omnia parent. 8 Sed multi mortales, dediti ventri atque somno, indocti incultique vitam sicuti peregrinantes transiere; quibus profecto contra naturam corpus voluptati, anima oneri fuit. Eorum ego vitam mortemque iuxta aestumo, quoniam de utraque siletur. 9 Verum enim vero is demum mihi vivere atque frui anima videtur, qui aliquo negotio intentus praeclari facinoris aut artis bonae famam quaerit. Sed in magna copia rerum aliud alii natura iter ostendit.",

"[3] 1 Pulchrum est bene facere rei publicae, etiam bene dicere haud absurdum est; vel pace vel bello clarum fieri licet; et qui fecere et qui facta aliorum scripsere, multi laudantur. 2 Ac mihi quidem, tametsi haudquaquam par gloria sequitur scriptorem et actorem rerum, tamen in primis arduum videtur res gestas scribere: primum, quod facta dictis exaequanda sunt; dehinc, quia plerique, quae delicta reprehenderis, malevolentia et invidia dicta putant, ubi de magna virtute atque gloria bonorum memores, quae sibi quisque facilia factu putat, aequo animo accipit, supra ea veluti ficta pro falsis ducit.

3 Sed ego adulescentulus initio, sicuti plerique, studio ad rem publicam latus sum ibique mihi multa advorsa fuere. Nam pro pudore, pro abstinentia, pro virtute audacia, largitio, avaritia vigebant. 4 Quae tametsi animus aspernabatur insolens malarum artium, tamen inter tanta vitia imbecilla aetas ambitione corrupta tenebatur; 5 ac me, cum ab reliquorum malis moribus dissentirem, nihilo minus honoris cupido eadem, qua ceteros, fama atque invidia vexabat.")

Authors <- c("Catullus", "Cicero", "Sallust")

data <- tibble(Catullus, Cicero, Sallust)


selections <- c("Selection 1", "Selection 2", "Selection 3")

final_data <- data %>% 
  add_column(Selections = selections) 




```



```

